apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: login-api
  name: login-api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: login-api
  template:
    metadata:
      labels:
        service: login-api
    spec:
      containers:
      - image: curtbryan3rd/cb3-login-api
        name: login-api
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
      restartPolicy: Always